name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Release
      uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v1.0.0
          release_name: Release $v1.0.0
          body: |
            Changes in this Release
            - First Change aaa
            - Second Change bbb
          draft: false
          prerelease: false
