name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker images using cache
      run: |
        docker login docker.pkg.github.com --username tw26467 -p "${{ secrets.DOCKER_PASSWORD }}"
        docker tag docker_test docker.pkg.github.com/tw26467/actions-cpp/test:1.0
        docker push docker.pkg.github.com/tw26467/actions-cpp/test:1.0
