name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build docker images using cache
      if: contains(github.ref, 'refs/tags/v')
      run: |
          docker login docker.pkg.github.com --username "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
          docker build -t docker.pkg.github.com/tw26467/actions-cpp/test:${{{ GITHUB_TAG }} .
          docker push docker.pkg.github.com/tw26467/actions-cpp/test:${{ GITHUB_TAG }}
