name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Environment Printer
      uses: managedkaos/print-env@v1.0
      
    - uses: actions/checkout@v1
    - name: Build docker images using cache
      if: contains(github.ref, 'refs/tags/')
      run: |
        DOCKER_TAG="$(echo "${GITHUB_REF}" | awk -F/ '{print $NF}')"
        docker login docker.pkg.github.com --username "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"
        docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}/release:${DOCKER_TAG} .
        docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/release:${DOCKER_TAG}
        
