name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag: v1.0.09
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
