name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v1
    - name: Install conan && conan package tools
      run: |
        python -m pip install --upgrade pip
        pip install conan
        pip install conan_package_tools
    - uses: actions/checkout@v1
    - name: conan
      run: |
        conan install . -s compiler.libcxx=libstdc++11
    - name: cmake
      run: |
        find /home/runner/.conan -name '*.so*'
        cmake . -DCMAKE_TOOLCHAIN_FILE=conan_paths.cmake
        cmake --build .
        ctest --output-on-failure
    - name: Publish Docker Image to GPR
      uses: actions/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'test-docker-action'
        TAG: 'my-optional-tag-name'
        DOCKERFILE_PATH: 'argo/gpu.Dockerfile'
        BUILD_CONTEXT: 'argo/'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
